kind: pipeline
type: docker
name: vaultwarden-deploy

steps:
  - name: deploy
    image: docker:latest
    commands:
      - docker compose down
      - docker compose pull
      - docker compose up -d

    environment:
      VAULTWARDEN_ADMIN_TOKEN:
        from_secret: VAULTWARDEN_ADMIN_TOKEN

trigger:
  branch:
    - main
  event:
    - push
