kind: pipeline
type: docker
name: vaultwarden-deploy

steps:
  - name: deploy
    image: docker/compose:latest
    commands:
      - docker-compose down
      - docker-compose pull
      - docker-compose up -d
    volumes:
      - name: docker-sock
        path: /var/run/docker.sock
    environment:
      VAULTWARDEN_ADMIN_TOKEN:
        from_secret: VAULTWARDEN_ADMIN_TOKEN
    when:
      branch:
        - main
      event:
        - push

volumes:
  - name: docker-sock
    host:
      path: /var/run/docker.sock

trigger:
  branch:
    - main
  event:
    - push

